name: "🛡️ Reusable Quality Checks"

on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  composer-install-args: "--no-progress --no-interaction --prefer-dist --no-scripts"
  php-extensions: "sodium"

jobs:
  composer:
    name: "🏗 PHP & Composer Setup"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        name: 👞 Checkout

      - uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6
        name: 📀 Install Dependencies
        with:
          args: ${{ env.composer-install-args }}
          php_version: ${{ inputs.php_version }}
          php_extensions: ${{ env.php-extensions }}

      - name: 🧪 Composer Validate
        run: composer validate --strict

      - name: 🛡️ Composer Audit
        run: composer audit

  check:
    needs: composer
    name: "🛡️ Static Analysis"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        name: 👞 Checkout

      - name: 📅 Setup PHP ${{ inputs.php_version }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ inputs.php_version }}
          extensions: ${{ env.php-extensions }}
          tools: composer

      - uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6
        name: 📀 Install Dependencies
        with:
          args: ${{ env.composer-install-args }}
          php_version: ${{ inputs.php_version }}
          php_extensions: ${{ env.php-extensions }}

      - name: 🔍 PHPStan Analysis
        id: phpstan
        run: composer phpstan

      - name: 🛃 Code Style (PHPCS)
        id: phpcs
        if: success() || steps.phpstan.outcome == 'failure'
        run: composer phpcs

      - name: ♻️ Rector (dry run)
        id: rector
        if: success() || steps.phpstan.outcome == 'failure' || steps.phpcs.outcome == 'failure'
        run: composer rector:check

      - name: 🧪 Unit Tests
        if: success() || steps.phpstan.outcome == 'failure' || steps.phpcs.outcome == 'failure' || steps.rector.outcome == 'failure'
        run: composer phpunit

